# Generated by Django 3.2.7 on 2023-04-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=10, unique=True)),
                ('balance', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
            ],
        ),
    ]
