CREATE OR REPLACE STREAM "WITH_CREATION_TIMESTAMP" ("hashtag" VARCHAR(1024), "creation_timestamp" TIMESTAMP,"created_at" VARCHAR(32));

CREATE OR REPLACE PUMP "EXTRACT_TIMESTAMP_PUMP" AS INSERT INTO "WITH_CREATION_TIMESTAMP"
SELECT STREAM "hashtag", CHAR_TO_TIMESTAMP('E MMM dd HH:mm:ss Z yyyy', "created_at") AS "creation_timestamp", "created_at"
FROM "SOURCE_SQL_STREAM_001"
WHERE "hashtag" IS NOT NULL;

CREATE OR REPLACE STREAM "DESTINATION_SQL_STREAM" ("ingest_time" TIMESTAMP, "creation_time" TIMESTAMP, "hashtag" VARCHAR(1024), "count" INTEGER);

CREATE OR REPLACE PUMP "STREAM_PUMP" AS INSERT INTO "DESTINATION_SQL_STREAM"
SELECT STREAM
  STEP("WITH_CREATION_TIMESTAMP".ROWTIME BY INTERVAL '60' SECOND) AS "ingest_time",
  STEP("WITH_CREATION_TIMESTAMP"."creation_timestamp" BY INTERVAL '60' SECOND) AS "creation_time",
  "hashtag",
  COUNT(*) AS "count"
FROM "WITH_CREATION_TIMESTAMP"
GROUP BY "hashtag",
  STEP("WITH_CREATION_TIMESTAMP".ROWTIME BY INTERVAL '60' SECOND),
  STEP("WITH_CREATION_TIMESTAMP"."creation_timestamp" BY INTERVAL '60' SECOND);