CREATE OR REPLACE STREAM TOP_HASH_TAGS (
  "hashtag" VARCHAR(1024),
  "MOST_FREQUENT_VALUES" BIGINT
);

CREATE OR REPLACE PUMP "STREAM_PUMP" AS
    INSERT INTO "TOP_HASH_TAGS"
    SELECT STREAM *
        FROM TABLE (TOP_K_ITEMS_TUMBLING(
            CURSOR(SELECT STREAM "hashtag" FROM "SOURCE_SQL_STREAM_001" WHERE "hashtag" IS NOT NULL),
            'hashtag',
            5,
            60)
        );

CREATE OR REPLACE STREAM "DESTINATION_SQL_STREAM" (created_at VARCHAR(32), text VARCHAR(280), lang VARCHAR(4));

CREATE OR REPLACE PUMP "DESTINATION_STREAM_PUMP" AS INSERT INTO "DESTINATION_SQL_STREAM"
SELECT STREAM "created_at", "text", "lang"
FROM "SOURCE_SQL_STREAM_001" AS source
JOIN TOP_HASH_TAGS OVER (RANGE INTERVAL '5' MINUTE PRECEDING) AS top
 ON top."hashtag" = source."hashtag";

