CREATE OR REPLACE STREAM "DESTINATION_SQL_STREAM" (created_at VARCHAR(32), text VARCHAR(280), lang VARCHAR(4));

CREATE OR REPLACE PUMP "STREAM_PUMP" AS INSERT INTO "DESTINATION_SQL_STREAM"
SELECT STREAM "created_at", "text", "lang"
FROM "SOURCE_SQL_STREAM_001"
WHERE "lang" = 'en';