CREATE OR REPLACE STREAM DESTINATION_SQL_STREAM (
  "hashtag" VARCHAR(1024),
  "MOST_FREQUENT_VALUES" BIGINT
);

CREATE OR REPLACE PUMP "STREAM_PUMP" AS
    INSERT INTO "DESTINATION_SQL_STREAM"
    SELECT STREAM *
        FROM TABLE (TOP_K_ITEMS_TUMBLING(
            CURSOR(SELECT STREAM "hashtag" FROM "SOURCE_SQL_STREAM_001" WHERE "hashtag" IS NOT NULL),
            'hashtag',
            5,
            60)
        );