"""empty message

Revision ID: 18edfdee8bd4
Revises: 
Create Date: 2021-09-06 09:34:53.901532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18edfdee8bd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('dob', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'dob')
    # ### end Alembic commands ###
